// Auto-generated publications data - 2025-07-26T02:11:50.794526
// Do not edit this file directly, use scholar_scraper.py

window.PUBLICATIONS_DATA = {
  "scholar_stats": {
    "total_citations": 230,
    "h_index": 7,
    "i10_index": 7,
    "last_updated": "2025-07-26"
  },
  "publications": [
    {
      "title": "The association between mechanical ventilator compatible bed occupancy and mortality risk in intensive care patients with COVID-19: a national retrospective cohort study",
      "authors": [
        "H Wilde",
        "T Mellan",
        "I Hawryluk",
        "JM Dennis",
        "S Denaxas",
        "C Pagel",
        "A Duncan"
      ],
      "year": 2021,
      "venue": "BMC medicine 19 (1), 213, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:ufrVoPGSRksC",
      "annotations": [
        {
          "text": "Was interviewed on BBC Evening News and featured in a lot of international media coverage, see",
          "link": {
            "url": "https://medrxiv.altmetric.com/details/97586336",
            "text": "Altmetric"
          }
        }
      ]
    },
    {
      "title": "Hospital bed capacity and usage across secondary healthcare providers in England during the first wave of the COVID-19 pandemic: a descriptive analysis",
      "authors": [
        "BA Mateen",
        "H Wilde",
        "JM Dennis",
        "A Duncan",
        "N Thomas",
        "A McGovern"
      ],
      "year": 2021,
      "venue": "BMJ open 11 (1), e042945, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:Y0pCki6q_DkC",
      "annotations": []
    },
    {
      "title": "Hospital admissions linked to SARS-CoV-2 infection in children and adolescents: cohort study of 3.2 million first ascertained infections in England",
      "authors": [
        "H Wilde",
        "C Tomlinson",
        "BA Mateen",
        "D Selby",
        "HK Kanthimathinathan"
      ],
      "year": 2023,
      "venue": "bmj 382, 2023",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:Se3iqnhoufwC",
      "annotations": []
    },
    {
      "title": "Trends in 28-day mortality of critical care patients with coronavirus disease 2019 in the United Kingdom: a national cohort study, March 2020 to January 2021",
      "authors": [
        "JM Dennis",
        "AP McGovern",
        "NJ Thomas",
        "H Wilde",
        "SJ Vollmer",
        "BA Mateen"
      ],
      "year": 2021,
      "venue": "Critical Care Medicine 49 (11), 1895-1900, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:IjCSPb-OGe4C",
      "annotations": []
    },
    {
      "title": "Mitigating statistical bias within differentially private synthetic data",
      "authors": [
        "S Ghalebikesabi",
        "H Wilde",
        "J Jewson",
        "A Doucet",
        "S Vollmer",
        "C Holmes"
      ],
      "year": 2022,
      "venue": "Uncertainty in Artificial Intelligence, 696-705, 2022",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:_FxGoFyzp5QC",
      "annotations": []
    },
    {
      "title": "Foundations of Bayesian learning from synthetic data",
      "authors": [
        "H Wilde",
        "J Jewson",
        "S Vollmer",
        "C Holmes"
      ],
      "year": 2021,
      "venue": "International conference on artificial intelligence and statistics, 541-549, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:u-x6o8ySG0sC",
      "annotations": []
    },
    {
      "title": "Faking feature importance: A cautionary tale on the use of differentially-private synthetic data",
      "authors": [
        "O Giles",
        "K Hosseini",
        "G Mingas",
        "O Strickson",
        "L Bowler",
        "CR Smith",
        "H Wilde"
      ],
      "year": 2022,
      "venue": "arXiv preprint arXiv:2203.01363, 2022",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:LkGwnXOMwfcC",
      "annotations": []
    },
    {
      "title": "A national retrospective study of the association between serious operational problems and COVID-19 specific intensive care mortality risk",
      "authors": [
        "H Wilde",
        "JM Dennis",
        "AP McGovern",
        "SJ Vollmer",
        "BA Mateen"
      ],
      "year": 2021,
      "venue": "PLoS One 16 (7), e0255377, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:2osOgNQ5qMEC",
      "annotations": []
    },
    {
      "title": "Trends in Pediatric Hospital Admissions Caused or Contributed by SARS-CoV-2 Infection in England",
      "authors": [
        "H Wilde",
        "C Tomlinson",
        "BA Mateen",
        "D Selby",
        "HK Kanthimathinathan"
      ],
      "year": 2025,
      "venue": "The Journal of Pediatrics 276, 114370, 2025",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:d1gkVwhDpl0C",
      "annotations": []
    },
    {
      "title": "A recommendation and risk classification system for connecting rough sleepers to essential outreach services",
      "authors": [
        "H Wilde",
        "LL Chen",
        "A Nguyen",
        "Z Kimpel",
        "J Sidgwick",
        "A De Unanue"
      ],
      "year": 2021,
      "venue": "Data & Policy 3, e2, 2021",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:W7OEmFMy1HYC",
      "annotations": []
    },
    {
      "title": "A Methodological Framework for Assessing the Benefit of SARS-CoV-2 Vaccination following Previous Infection: Case Study of Five-to Eleven-Year-Olds",
      "authors": [
        "C Pagel",
        "H Wilde",
        "C Tomlinson",
        "B Mateen",
        "K Brown"
      ],
      "year": 2023,
      "venue": "Vaccines 11 (5), 988, 2023",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:9yKSN-GCB0IC",
      "annotations": []
    },
    {
      "title": "COEXI (S) T: modelling COVID-19 exit strategies for policy makers in the United Kingdom",
      "authors": [
        "G Bohner",
        "G Venkataraman",
        "H Wilde"
      ],
      "year": 2020,
      "venue": "See https://github. com/gbohner/coexist, 2020",
      "link": "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nkElOLUAAAAJ&citation_for_view=nkElOLUAAAAJ:eQOLeE2rZwMC",
      "annotations": []
    }
  ]
};
