// Auto-generated publications data - 2025-07-26T02:49:13.176351
// Do not edit this file directly, use scholar_scraper.py

window.PUBLICATIONS_DATA = {
  "scholar_stats": {
    "total_citations": 230,
    "h_index": 7,
    "i10_index": 7,
    "last_updated": "2025-07-26"
  },
  "publications": [
    {
      "title": "The association between mechanical ventilator compatible bed occupancy and mortality risk in intensive care patients with COVID-19: a national retrospective cohort study",
      "authors": [
        "Harrison Wilde",
        "Thomas Mellan",
        "Iwona Hawryluk",
        "John M Dennis",
        "Spiros Denaxas",
        "Christina Pagel",
        "Andrew Duncan",
        "Samir Bhatt",
        "Seth Flaxman",
        "Bilal A Mateen",
        "Sebastian J Vollmer"
      ],
      "year": 2021,
      "venue": "BMC medicine 19 (1), 213, 2021",
      "link": "https://link.springer.com/article/10.1186/s12916-021-02096-0",
      "annotations": [
        {
          "text": "This work featured in a lot of international media coverage, see",
          "link": {
            "url": "https://medrxiv.altmetric.com/details/97586336",
            "text": "Altmetric"
          }
        }
      ]
    },
    {
      "title": "Hospital bed capacity and usage across secondary healthcare providers in England during the first wave of the COVID-19 pandemic: a descriptive analysis",
      "authors": [
        "Bilal Akhter Mateen",
        "Harrison Wilde",
        "John M Dennis",
        "Andrew Duncan",
        "Nick Thomas",
        "Andrew McGovern",
        "Spiros Denaxas",
        "Matt Keeling",
        "Sebastian Vollmer"
      ],
      "year": 2021,
      "venue": "BMJ open 11 (1), e042945, 2021",
      "link": "https://bmjopen.bmj.com/content/11/1/e042945.abstract",
      "annotations": []
    },
    {
      "title": "Hospital admissions linked to SARS-CoV-2 infection in children and adolescents: cohort study of 3.2 million first ascertained infections in England",
      "authors": [
        "Harrison Wilde",
        "Christopher Tomlinson",
        "Bilal A Mateen",
        "David Selby",
        "Hari Krishnan Kanthimathinathan",
        "Padmanabhan Ramnarayan",
        "Pascale Du Pre",
        "Mae Johnson",
        "Nazima Pathan",
        "Arturo Gonzalez-Izquierdo",
        "Alvina G Lai",
        "Deepti Gurdasani",
        "Christina Pagel",
        "Spiros Denaxas",
        "Sebastian Vollmer",
        "Katherine Brown"
      ],
      "year": 2023,
      "venue": "bmj 382, 2023",
      "link": "https://www.bmj.com/content/382/bmj-2022-073639.abstract",
      "annotations": []
    },
    {
      "title": "Trends in 28-day mortality of critical care patients with coronavirus disease 2019 in the United Kingdom: a national cohort study, March 2020 to January 2021",
      "authors": [
        "John M Dennis",
        "Andrew P McGovern",
        "Nicholas J Thomas",
        "Harrison Wilde",
        "Sebastian J Vollmer",
        "Bilal A Mateen"
      ],
      "year": 2021,
      "venue": "Critical Care Medicine 49 (11), 1895-1900, 2021",
      "link": "https://journals.lww.com/ccmjournal/fulltext/2021/11000/Trends_in_28_Day_Mortality_of_Critical_Care.6.aspx",
      "annotations": []
    },
    {
      "title": "Mitigating statistical bias within differentially private synthetic data",
      "authors": [
        "Sahra Ghalebikesabi",
        "Harry Wilde",
        "Jack Jewson",
        "Arnaud Doucet",
        "Sebastian Vollmer",
        "Chris Holmes"
      ],
      "year": 2022,
      "venue": "Uncertainty in Artificial Intelligence, 696-705, 2022",
      "link": "https://proceedings.mlr.press/v180/ghalebikesabi22a.html",
      "annotations": []
    },
    {
      "title": "Foundations of Bayesian learning from synthetic data",
      "authors": [
        "Harrison Wilde",
        "Jack Jewson",
        "Sebastian Vollmer",
        "Chris Holmes"
      ],
      "year": 2021,
      "venue": "International conference on artificial intelligence and statistics, 541-549, 2021",
      "link": "http://proceedings.mlr.press/v130/wilde21a.html",
      "annotations": []
    },
    {
      "title": "Faking feature importance: A cautionary tale on the use of differentially-private synthetic data",
      "authors": [
        "Oscar Giles",
        "Kasra Hosseini",
        "Grigorios Mingas",
        "Oliver Strickson",
        "Louise Bowler",
        "Camila Rangel Smith",
        "Harrison Wilde",
        "Jen Ning Lim",
        "Bilal Mateen",
        "Kasun Amarasinghe",
        "Rayid Ghani",
        "Alison Heppenstall",
        "Nik Lomax",
        "Nick Malleson",
        "Martin O'Reilly",
        "Sebastian Vollmerteke"
      ],
      "year": 2022,
      "venue": "arXiv preprint arXiv:2203.01363, 2022",
      "link": "https://arxiv.org/abs/2203.01363",
      "annotations": []
    },
    {
      "title": "A national retrospective study of the association between serious operational problems and COVID-19 specific intensive care mortality risk",
      "authors": [
        "Harrison Wilde",
        "John M Dennis",
        "Andrew P McGovern",
        "Sebastian J Vollmer",
        "Bilal A Mateen"
      ],
      "year": 2021,
      "venue": "PLoS One 16 (7), e0255377, 2021",
      "link": "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0255377",
      "annotations": []
    },
    {
      "title": "Trends in Pediatric Hospital Admissions Caused or Contributed by SARS-CoV-2 Infection in England",
      "authors": [
        "Harrison Wilde",
        "Christopher Tomlinson",
        "Bilal A Mateen",
        "David Selby",
        "Hari Krishnan Kanthimathinathan",
        "Spiros Denaxas",
        "Seth Flaxman",
        "Sebastian Vollmer",
        "Christina Pagel",
        "Katherine Brown",
        "CVD-COVID-UK/COVID-IMPACT Consortium"
      ],
      "year": 2025,
      "venue": "The Journal of Pediatrics 276, 114370, 2025",
      "link": "https://www.sciencedirect.com/science/article/pii/S0022347624004736",
      "annotations": []
    },
    {
      "title": "A recommendation and risk classification system for connecting rough sleepers to essential outreach services",
      "authors": [
        "Harrison Wilde",
        "Lucia L Chen",
        "Austin Nguyen",
        "Zoe Kimpel",
        "Joshua Sidgwick",
        "Adolfo De Unanue",
        "Davide Veronese",
        "Bilal Mateen",
        "Rayid Ghani",
        "Sebastian Vollmer"
      ],
      "year": 2021,
      "venue": "Data & Policy 3, e2, 2021",
      "link": "https://www.cambridge.org/core/journals/data-and-policy/article/recommendation-and-risk-classification-system-for-connecting-rough-sleepers-to-essential-outreach-services/55E067F857ED9F1592EF1A0B3CE1E286",
      "annotations": []
    },
    {
      "title": "A Methodological Framework for Assessing the Benefit of SARS-CoV-2 Vaccination following Previous Infection: Case Study of Five-to Eleven-Year-Olds",
      "authors": [
        "Christina Pagel",
        "Harrison Wilde",
        "Christopher Tomlinson",
        "Bilal Mateen",
        "Katherine Brown"
      ],
      "year": 2023,
      "venue": "Vaccines 11 (5), 988, 2023",
      "link": "https://www.mdpi.com/2076-393X/11/5/988",
      "annotations": []
    },
    {
      "title": "COEXI (S) T: modelling COVID-19 exit strategies for policy makers in the United Kingdom",
      "authors": [
        "Gergo Bohner",
        "Gaurav Venkataraman",
        "Harrison Wilde"
      ],
      "year": 2020,
      "venue": "See https://github. com/gbohner/coexist, 2020",
      "link": "https://scholar.google.com/scholar?cluster=11153521763373616311&hl=en&oi=scholarr",
      "annotations": []
    }
  ]
};
